### PR TITLE
Fix the export error

### LINKED ISSUE #76: Broken build after updates to 2.6.1
After updates to 2.6.1 I start to recieve this error
```
node_modules/immutability-helper/index.d.ts(4,1): error TS2309: An export assignment cannot be used in a module with other exported elements.
node_modules/immutability-helper/index.d.ts(6,18): error TS2395: Individual declarations in merged declaration 'update' must be all exported or all local.
node_modules/immutability-helper/index.d.ts(8,18): error TS2395: Individual declarations in merged declaration 'update' must be all exported or all local.
node_modules/immutability-helper/index.d.ts(36,7): error TS2315: Type 'MapAndSetOperators' is not generic.

```
Any ideas how this could be fixed?

### PR DESCRIPTION
**Pull request by andreiglingeanu**
Fixes #76 

This will:

- properly export `update` function
- make `MapAndSetOperators` generic

cc. @kolodny

### CODE REVIEW

**Comment by kolodny** [comment]
I'm fine with this PR, but is there any way to include a ts build/check step to `npm test` so that regressions on the `.d.ts` file don't come back to bite us?

File: index.d.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
+// Type definitions for immutability-helper
+// Project: Immutability helper
+
+export default update
```
Comment (ghost) [inline index.d.ts]: In the source code this is `module.exports =`, so it should be declared as `export =`.
See https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default

**Review by ghost — COMMENTED** [review]
This looks better than what's in DefinitelyTyped.
Have you considered using overloading instead of a union of queries? This would prevent you from e.g. using an `ArrayOperator` on something that's not an array.
```ts
declare function update<T>(data: ReadonlyArray<T>, query:  update.ArrayOperator<T>): ReadonlyArray<T>
declare function update<T>(data: ReadonlySet<T>, query: { $add: ReadonlyArray<T> } | { $remove: ReadonlyArray<T> }): ReadonlySet<T>
declare function update<K, V>(data: ReadonlyMap<K, V>, query: { $add: ReadonlyArray<[K, V]> } | { $remove: ReadonlyArray<K> }): ReadonlyMap<K, V>
declare function update<K extends string, T extends { readonly [key in K]: boolean }>(data: T, query: { $toggle: ReadonlyArray<K> }): T;
...etc...
```
...although I can't figure out how you would strongly-type nested queries without conditional types (Microsoft/TypeScript#12424).

If you're interested in testing, [`dtslint`](https://github.com/Microsoft/dtslint) can be run outside of DefinitelyTyped. (But make sure to remove the `// Type definitions for immutability-helper` header or it will think you're on DefinitelyTyped.)

**Comment by andreiglingeanu** [comment]
Oh, thanks. I'll get over everything a covert it into a commit soon.

And yes, I have seen https://github.com/Microsoft/TypeScript/issues/12424 while researching a way to provide stronger types for the lib. I believe overloading is way better than having unions, thanks for that. But yeah, without conditional types we are indeed loosing some information about the generic type `<T>`.

File: index.d.ts (hunk 1 above)
Comment (andreiglingeanu) [reply index.d.ts]: Cool, thanks

**Comment by andreiglingeanu** [comment]
Hey @kolodny, now you can run `npm run test-dtslint` in order to verify the validity of the types, sorry for not getting them correct from the first pass

@andy-ms could you please see if typings are in a better shape now?

**Comment by ghost** [comment]
@andreiglingeanu It looks good, but it doesn't seem like it will allow you to push to an array that's nested as a property? You would have to include `$push` in the `Query` type for that to work.

**Comment by andreiglingeanu** [comment]
Oh, my bad! For some kind of a reason I thought the array would be only on the first level.

I'll fix the typings, thanks.

**Comment by andreiglingeanu** [comment]
@andy-ms pushed the change. Now arrays, Map & Sets can be nested into objects. Does that look okay?

File: index.d.ts [hunk 2]
```diff
@@ -6,39 +6,47 @@ export = update
...
   | {$merge: Partial<T>}
   | {$apply: (old: T) => any}
   | ((old: T) => any)
+type ArrayOperators<T> =
+  | {$push: T}
+  | {$unshift: T}
+  | {$splice: Array<[number, number]>}
+  | {$splice: Array<[number, number]>}
+
+type MapAndSetOperators<T> = {$add: any[]} | {$remove: string[]}
```
Comment (ghost) [inline index.d.ts]: For a Map, shouldn't this be `$remove: K[]` and `$add: [K, V][]`?
Similarly, for a Set you would remove/ add `T`, not `string`.

**Comment by andreiglingeanu** [comment]
Yeah, missed that. A strong limitation is that I won't be able to type properly the nested `Map` in a `Query` without conditional types, but we should be good for now.

File: index.d.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+  data: ReadonlyMap<K, V>,
+  query: MapOperators<K, V>,
+): ReadonlyMap<K, V>
+
+type Tree<T> = {[K in keyof T]?: Query<T[K]>}
+type Query<T> =
+  | Tree<T>
+  | ObjectOperators<T>
+  | ArrayOperators<T>
+  | SetOperators<T>
```
Comment (ghost) [inline index.d.ts]: This would just be `ArrayOperators<any>` and `SetOperators<any>` since `T` here is the type of the object itself, not the type of its elements.

File: index.d.ts [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+
+export = update
+
+// declare function update<T>(data: T, query: update.Query<T>): T
+declare function update<T>(
+  data: ReadonlyArray<T>,
+  query: ArrayOperators<T>,
+): ReadonlyArray<T>
+
+declare function update<T>(data: T, query: Query<T>): object
```
Comment (ghost) [inline index.d.ts]: This should be the last overload so that the `ReadonlySet` and `ReadonlyMap` ones are tried first.

File: index.d.ts [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+  | ObjectOperators<T>
+  | ArrayOperators<any>
+  | SetOperators<any>
+
+type ObjectOperators<T> =
+  | {$set: any}
+  | {$toggle: Array<keyof T>}
+  | {$unset: Array<keyof T>}
+  | {$merge: Partial<T>}
+  | {$apply: (old: T) => any}
```
Comment (ghost) [inline index.d.ts]: Should this be `=> T`?

**Review by ghost — APPROVED** [review]
Last comment

**Comment by andreiglingeanu** [comment]
@andy-ms Thanks, learned a lot :)

**Comment by kolodny** [comment]
Awesome! Thanks for this. I'm going to add `tslint` to the build process so that it runs on travis. Are there any administrative steps to take after making a release, for example should there be a PR to remove `immutability-helper` from `DefinitelyTyped`

**Comment by kolodny** [comment]
Also I imagine that #79 can be closed, is that correct?

**Comment by andreiglingeanu** [comment]
Awesome!

@kolodny after we PR `DefinitelyType` yes, #79 can be closed

**Comment by kolodny** [comment]
Great, published to `v2.6.3`
