### ISSUE TITLE
Broken build after updates to 2.6.1

### ISSUE THREAD

**Issue by taras-samkvoskyi** [kolodny/immutability-helper#76]
After updates to 2.6.1 I start to recieve this error
```
node_modules/immutability-helper/index.d.ts(4,1): error TS2309: An export assignment cannot be used in a module with other exported elements.
node_modules/immutability-helper/index.d.ts(6,18): error TS2395: Individual declarations in merged declaration 'update' must be all exported or all local.
node_modules/immutability-helper/index.d.ts(8,18): error TS2395: Individual declarations in merged declaration 'update' must be all exported or all local.
node_modules/immutability-helper/index.d.ts(36,7): error TS2315: Type 'MapAndSetOperators' is not generic.

```
Any ideas how this could be fixed?

**Comment by kolodny** [comment]
I just rolled that change back. @gnapse Any ideas what happened?

**Comment by kolodny** [comment]
whoops, meant to tag @andreiglingeanu

**Comment by andreiglingeanu** [comment]
@kolodny created a pull request with a fix
